Resources:
        CrustyTestBucket:
                Type: AWS::S3::Bucket
                Properties:
                        BucketName: crust-test-site
                        WebsiteConfiguration:
                                ErrorDocument: error.html
                                IndexDocument: index.html
        CrustyBucketPolicy:
                Type: AWS::S3::BucketPolicy
                Properties:
                        Bucket: !Ref CrustyTestBucket
                        PolicyDocument:
                                Version: 2012-10-17
                                Statement:
                                        - Sid: PublicReadGetObject
                                          Effect: Allow
                                          Principal: "*"
                                          Action: "s3:GetObject"
                                          Resource: "arn:aws:s3:::crust-test-site/*"
